var User = require( "/App-Server/User" );
var Group = require( "/App-Server/Group" );
var Post = require( "/App-Server/Post" );

var UGPGroup = require( "./UGPGroup" );

function CookieManager() {
	// TODO : Refactoring needed for these two functions
	var getPostFileList = function( postCookie ) {
		fileList = [];

		return fileList;
	}

	// TODO : retrieveInfoFromCookies can be done here
	this.parseCookies = function( request ) {
	    var list = {},
	        rc = request.headers.cookie;

	    rc && rc.split(';').forEach( function( cookie ) {
	        var parts = cookie.split( '=' );
	        list[parts.shift().trim()] = decodeURI( parts.join( '=' ) );
	    });

	    return list;
	}

	this.retrieveInfoFromCookies = function( cookies ) {
		if( cookies['verified'] == 'false' ) {
			return null;
		} else {
			var userCookie = cookies['user'];
			var groupCookie = cookies['group'];
			var postCookie = cookies['posts'];

			var user = new User( userCookie['userId'], userCookie['userName'], groupCookie['groupId'], userCookie['status'], userCookie['condition'] );
			var group = new Group( groupCookie['groupName'], groupCookie['groupOwner'], groupCookie['gPostFile']['filename'], groupCookie['createdAt'] );
			var post[] = getPostFileList( postCookie );
		}

		return new UGPGroup( user, group, post );
	}

	var cookiesForStranger = function() {
		return { "verified" : "false" };
	}

	var cookiesForBeginner = function( user ) {
		return {
			["verified"]: "true",
			["user"]: {
				["userName"]: user.getUserName(),
				["userFile"]: user.getUserFile(),
				["groupName"]: user.getGroupName(),
				["createdAt"]: user.getCreatedAt(),
				["group"]: "null"
			}
		}
	}

	var cookiesForUser = function( user, group ) {
		return {
			["verified"]: "true",
			["user"]: {
				["userName"]: user.getUserName(),
				["userFile"]: user.getUserFile(),
				["group"]: {
					["groupName"]: group.getGroupName(),
					["groupOwner"]: gorup.getGroupOwner(),
					["groupFile"]: group.getGroupFile(),
				}
			}
		};
	}

	// DESIGN : Cookie is json format. Parents are "User", "Group", "Posts".
	//		  : Cookie is generated by builder pattern.
	this.generateCookies = function( user, group ) {
		var cookies = {};
		if( user == null ) {
			return cookiesForStranger();
		} else {
			if( group == null ) {
				return cookiesForBeginner( user );
			} else {
				return cookiesForUser( user, group );
			}
		}
	}
}

module.exports = CookieParser;